# -*- coding: utf-8 -*-
"""project1_refactored.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3dRKYWiVnuAs-zyxWnkszcNuCCTL3WL
"""

# lab 14 refactoring :
    # define local variable before calculations
    # change to explicit variable name + add spaces around operators
    # use num_number to define range
    # removal of useless while loop

def russian_roulette():
    import time
    import random
    
    players = []
    
# to make a robust input of players that should be a type number and comprised within limit from 2 to 6
    while True:    
        try:
            num_player = int(input("Enter a number of players (2-6): "))
        except ValueError: # used to check whether the input is an int
            print("Not a number, please insert a number!")
        else: # is accessed if the input is a int
            if num_player <= 1 or num_player > 6:
                print("Number of players should be comprised within 2 to 6")
            else: # if number is in limit, break the loop
                break
                
# to create an input of players use a for loop that breaks when counter equals to number of players input or 6 - max number of players   
    for i in range(num_player): 
        name = input("Please enter your name ")
        players.append(name)
        if i+1 == num_player or i+1 == 6:
            break

# Game starts with round 0, to determine "deadnumber" use of a random function 
    round = 0
    dead_number = random.randint(1,6)
    
# game will continue till the round is less than 6, max number of numbers, when round reaches deadnumber => exit of the loop

# till game is on the for loop will scan each player till the round reaches deadnumber, condition at which loop exits
    for i in range(0,len(players)): 
            round += 1
            print("\nRound",round) #output to show a current round
            print(players[i], "your time to play")
            print(input("press enter to start the game")) #to start the game player press enter
            # Timer 3,2,1
            for t in range(3,0,-1):
                info='shoot in '+str(t)+'s'
                print(info,end='\r')
                time.sleep(1)

            if round != dead_number: #if current round is not equal to "dead number" - game continue, else game stops
                print("CLIC:",players[i],"you're still alive! this is your lucky day...for now ") 
            else:
                print("BOOM:",players[i],"OOps!you're dead")
                print("Gameover")
                break

russian_roulette()

